version: '2'
services:
  node1:
    image: medvekoma/cassandra
    ports:
      - "9042:9042"
      - "9160:9160"
    restart: unless-stopped
  node2:
    image: medvekoma/cassandra
    links:
      - node1:seed1
    environment:
      CASSANDRA_SEEDS: seed1
    restart: unless-stopped
  node3:
    image: medvekoma/cassandra
    links:
      - node1:seed1
      - node2:seed2
    environment:
      CASSANDRA_SEEDS: seed1,seed2
    restart: unless-stopped
